name: book_bank
version: 1.0.0+1
publish_to: none
description: Book Bank
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.3.0


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
assets:
    - assets/
    - assets/images/
flutter: 
  uses-material-design: true


